from .Test_ImageData_GET import Test_ImageData_GET
from .Test_ImageData_POST import Test_ImageData_POST
from .Test_ImageData_PUT import Test_ImageData_PUT
from .Test_ImageDataId_PUT import Test_ImageDataId_PUT
from .Test_ImageId_DELETE import Test_ImageId_DELETE
from .Test_login_POST import Test_login_POST