name: Update Live Lambda Aliases
on:
  push:
    branches:
      - main
  
jobs:
  unittest:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      success-local: ${{ steps.run-local-tests.outputs.success }}
      success-dev-stage: ${{ steps.run-local-tests.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup python environment for unit tests
        run: pip install requests

      - name: Run local unit tests
        id: run-local-tests
        run: bash .github/scripts/run-unit-tests.sh LOCAL

      - name: Run unit tests on dev stage
        id: run-dev-stage-tests
        run: bash .github/scripts/run-unit-tests.sh DEV
  
  update-aliases:
    name: Update Live Lambda Aliases
    runs-on: ubuntu-latest
    if: {{ jobs.unittest.outputs.success-local == 0 && jobs.unittest.outputs.success-dev-stage == 0}}
    # outputs:
    #   changes: ${{ steps.find-updated-lambda-functions.outputs.updated_funcs_count }}
    #   changed_funcs: ${{ steps.find-updated-lambda-functions.outputs.updated_funcs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy changes to Lambda
        run: bash .github/scripts/update-live-lambda-aliases.sh